# Generated by Django 5.1.4 on 2025-01-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientfeedback',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client_images/'),
        ),
    ]
