# Generated by Django 5.1.4 on 2025-01-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_alter_clientfeedback_options_clientfeedback_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='To‘liq ismi')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochta')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon raqami')),
                ('car_type', models.CharField(max_length=50, verbose_name='Avtomobil turi')),
                ('pick_up_location', models.CharField(max_length=255, verbose_name='Jo‘nab ketish joyi')),
                ('drop_off_location', models.CharField(max_length=255, verbose_name='Yetkazib berish joyi')),
                ('pick_up_date', models.DateField(verbose_name='Jo‘nab ketish sanasi')),
                ('return_date', models.DateField(verbose_name='Qaytish sanasi')),
                ('additional_note', models.TextField(blank=True, null=True, verbose_name='Qo‘shimcha eslatma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
