# Generated by Django 5.1.4 on 2025-01-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pick_up_date',
            field=models.CharField(max_length=255, verbose_name='Jo‘nab ketish sanasi'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_date',
            field=models.CharField(max_length=255, verbose_name='Qaytish sanasi'),
        ),
    ]
