# Generated by Django 5.1.4 on 2025-01-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_alter_booking_pick_up_date_alter_booking_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Tekshirildimi?'),
        ),
    ]
