# Generated by Django 5.1.4 on 2025-01-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_booking_is_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('opening_hours', models.CharField(max_length=255, verbose_name='Ish vaqti')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('google_maps_iframe', models.TextField(verbose_name='Google Maps iframe')),
            ],
            options={
                'verbose_name': 'Aloqa sahifasi',
                'verbose_name_plural': 'Aloqa sahifalari',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('subject', models.CharField(max_length=150, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Tekshirildimi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
            },
        ),
    ]
