# Generated by Django 5.1.4 on 2025-01-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_alter_clientfeedback_options_alter_about_button_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Biz haqimizda', 'verbose_name_plural': 'Biz haqimizda'},
        ),
        migrations.AlterModelOptions(
            name='promovideo',
            options={'verbose_name': 'Promo Video', 'verbose_name_plural': 'Promo Videolar'},
        ),
    ]
