# Generated by Django 5.1.4 on 2025-01-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_alter_car_options_alter_carbrand_options_and_more'),
        ('home_app', '0009_homeluxurycars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeluxurycars',
            name='cars',
            field=models.ManyToManyField(blank=True, null=True, to='car_app.car', verbose_name='Mashinalar'),
        ),
    ]
