# Generated by Django 5.1.4 on 2025-03-05 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0010_alter_homeluxurycars_cars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Aloqa sahifasi', 'verbose_name_plural': 'Aloqa sahifasi'},
        ),
        migrations.AlterModelOptions(
            name='promovideo',
            options={'verbose_name': 'Promo Video', 'verbose_name_plural': 'Promo Video'},
        ),
    ]
