# Generated by Django 5.1.4 on 2025-01-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='one_day_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='one_month_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='one_week_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
