# Generated by Django 5.1.4 on 2025-01-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_car_one_day_price_car_one_month_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
