# Generated by Django 5.1.4 on 2025-01-28 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_carbrand_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-id'], 'verbose_name': 'Avtomobil', 'verbose_name_plural': 'Avtomobillar'},
        ),
        migrations.AlterModelOptions(
            name='carbrand',
            options={'verbose_name': 'Avtomobil brendi', 'verbose_name_plural': 'Avtomobil brendlari'},
        ),
        migrations.AlterModelOptions(
            name='carcategory',
            options={'verbose_name': 'Avtomobil kategoriyasi', 'verbose_name_plural': 'Avtomobil kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='carcosiness',
            options={'verbose_name': 'Avtomobil qulayligi', 'verbose_name_plural': 'Avtomobil qulayliklari'},
        ),
        migrations.AlterModelOptions(
            name='carimage',
            options={'verbose_name': 'Avtomobil rasmi', 'verbose_name_plural': 'Avtomobil rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='cartype',
            options={'verbose_name': 'Avtomobil turi', 'verbose_name_plural': 'Avtomobil turlari'},
        ),
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_app.carbrand', verbose_name='Brend'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_app.carcategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_app.cartype', verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(max_length=255, verbose_name='Eshiklar'),
        ),
        migrations.AlterField(
            model_name='car',
            name='luggage',
            field=models.CharField(max_length=255, verbose_name='Bagaj'),
        ),
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=models.ImageField(upload_to='cars/', verbose_name='Asosiy rasm'),
        ),
        migrations.AlterField(
            model_name='car',
            name='one_day_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bir kunlik narx'),
        ),
        migrations.AlterField(
            model_name='car',
            name='one_month_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bir oylik narx'),
        ),
        migrations.AlterField(
            model_name='car',
            name='one_week_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bir haftalik narx'),
        ),
        migrations.AlterField(
            model_name='car',
            name='passengers',
            field=models.CharField(max_length=255, verbose_name='Yolovchilar'),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Avtomobil nomi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='Auto', max_length=255, verbose_name='Uzatma'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='image',
            field=models.ImageField(upload_to='car_brands/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Brend nomi'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='image',
            field=models.ImageField(upload_to='car_categories/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='carcosiness',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosinesses', to='car_app.car', verbose_name='Avtomobil'),
        ),
        migrations.AlterField(
            model_name='carcosiness',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Qulaylik nomi'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_app.car', verbose_name='Avtomobil'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='car-images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Rasm nomi'),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='image',
            field=models.ImageField(upload_to='car_types/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
    ]
