# Generated by Django 5.1.4 on 2025-03-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_alter_car_options_alter_carbrand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Orqa fon rasmi'),
        ),
    ]
