# Generated by Django 5.1.4 on 2025-01-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('favicon', models.FileField(upload_to='favicons/')),
                ('site_author', models.TextField()),
                ('site_keywords', models.TextField()),
                ('site_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('whatsapp_phone', models.CharField(max_length=255)),
                ('telegram_phone', models.CharField(max_length=255)),
                ('telegram_username', models.CharField(max_length=255)),
                ('header_logo', models.ImageField(upload_to='logos/')),
                ('footer_logo', models.ImageField(upload_to='logos/')),
                ('footer_text', models.TextField()),
                ('copyright_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
