# Generated by Django 5.1.4 on 2025-01-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_sitesettings_address_sitesettings_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('token', models.TextField()),
                ('admins', models.CharField(max_length=255)),
            ],
        ),
    ]
