# Generated by Django 5.1.4 on 2025-01-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_telegrambotconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosettings',
            name='favicon',
            field=models.FileField(upload_to='favicons/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='site_author',
            field=models.TextField(verbose_name='Sayt muallifi'),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='site_description',
            field=models.TextField(verbose_name='Sayt tavsifi'),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='site_keywords',
            field=models.TextField(verbose_name='Sayt kalit so‘zlari'),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sayt nomi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.TextField(verbose_name='Mualliflik huquqi matni'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_logo',
            field=models.ImageField(upload_to='logos/', verbose_name='Pastki logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(verbose_name='Pastki matn'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_logo',
            field=models.ImageField(upload_to='logos/', verbose_name='Bosh logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_phone',
            field=models.CharField(max_length=255, verbose_name='Telegram telefon raqami'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_username',
            field=models.CharField(max_length=255, verbose_name='Telegram foydalanuvchi nomi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_phone',
            field=models.CharField(max_length=255, verbose_name='WhatsApp telefon raqami'),
        ),
        migrations.AlterField(
            model_name='socialnetworks',
            name='icon',
            field=models.CharField(max_length=255, verbose_name='Ijtimoiy tarmoq ikonkasi'),
        ),
        migrations.AlterField(
            model_name='socialnetworks',
            name='link',
            field=models.CharField(max_length=255, verbose_name='Ijtimoiy tarmoq havolasi'),
        ),
        migrations.AlterField(
            model_name='socialnetworks',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Ijtimoiy tarmoq nomi'),
        ),
        migrations.AlterField(
            model_name='telegrambotconfig',
            name='admins',
            field=models.CharField(max_length=255, verbose_name='Adminlar'),
        ),
        migrations.AlterField(
            model_name='telegrambotconfig',
            name='token',
            field=models.TextField(verbose_name='Bot tokeni'),
        ),
        migrations.AlterField(
            model_name='telegrambotconfig',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Bot foydalanuvchi nomi'),
        ),
    ]
