# Generated by Django 5.1.4 on 2025-01-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_alter_seosettings_favicon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seosettings',
            options={'verbose_name': 'SEO Sozlamalari', 'verbose_name_plural': 'SEO Sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Sayt Sozlamalari', 'verbose_name_plural': 'Sayt Sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='socialnetworks',
            options={'verbose_name': 'Ijtimoiy Tarmoq', 'verbose_name_plural': 'Ijtimoiy Tarmoqlar'},
        ),
        migrations.AlterModelOptions(
            name='telegrambotconfig',
            options={'verbose_name': 'Telegram Bot Konfiguratsiyasi', 'verbose_name_plural': 'Telegram Bot Konfiguratsiyalari'},
        ),
    ]
